server:
  port: 8081
spring:
  cloud:
    openfeign:
      compression:
        request:
          mime-types: text/xml,application/xml,application/json
feign:
  client:
    config:
      default:
        loggerLevel: full
  name:
    site: swapdev
  url:
    site: https://swapi.dev/api/
spring-doc:
  swagger-ui:
    enabled: true